# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
author_name: Jesse Squire
title: Jesse Squire
short_title: Jesse Squire's Blog
email: jesse.squire@gmail.com
description: The technical blog and personal site of Jesse Squire.
baseurl: ""
url: "https://www.jessesquire.com"
title_description: >-
    <p>Jesse is a software engineer on the Azure Developer Platform team at Microsoft. He used to work on Halo at 343 Industries.</p>
    <p>This is the place where Jesse shares his thoughts on technology, code, software engineering and, occasionally, a personal thought or two.</p>
    <p>All views expressed are his own &ndash; especially those regarding the divinity of Hello Kitty.</p>
title_image: https://0.gravatar.com/avatar/fbe5310c4d5a64a88aeeb83676b28a81?s=500&d=mm
github_repository: https://github.com/jsquire/jessesquire.com
post_limit: 10

# External Resource Settings
display_sharing: true
google_analytics: UA-112031291-1
disqus_account: jesse-squire

# Social usernames/URLs
twitter_username: jesse_squire
github_username: jsquire
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/jessesquire
stackoverflow_link: https://stackoverflow.com/users/159548/jesse-squire?tab=profile
google_plus_link:
xing_link:
facebook_link:

# Footer
footer_left: "Carte Noire theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# SEO Settings (specific to jekyll-seo-tag)
# It also makes use of the following site-settings: title, description, url,
author: Jesse Squire
author:
  twitter: jesse_squire
logo: https://0.gravatar.com/avatar/fbe5310c4d5a64a88aeeb83676b28a81?s=500&d=mm
twitter:
  username: jesse_squire
social:
  name: Jesse Squire
  links:
    - https://twitter.com/Jesse_Squire
    - https://www.linkedin.com/in/jessesquire
    - https://github.com/jsquire
    - https://stackoverflow.com/users/159548/jesse-squire?tab=profile

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

  # Rouge Options â€º https://github.com/jneen/rouge#full-options
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - hamburgers

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
